project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  site-url: "https://MackKroll.github.io/Portfolio/"
  repo-url: "https://github.com/MackKroll/Portfolio"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projectBackground.qmd
      - model.qmd
      - results.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



